# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 088e02f0778efd6aff18e3cec75fa874b47dcf91a316f1f854e5979ccd7efdda1e9dd8c405b3848df241e571a2338e9fa4b4e7046235bcfa98066dfaddbd56a8

test:
  secret_key_base: c7c7cb607a4d2fa74707171d01c36a39300177472023da4820b29b1efc7f50403f1ba1f51adbfad114bf110a0b6e0244afc0c7aee87e431a2d71486e2a73e7ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
